# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/jobbsokerkompetanse
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  # NB: pus-decorator sine helsesjekker
  liveness:
    path: jobbsokerkompetanse/internal/isAlive
  readiness:
    path: jobbsokerkompetanse/internal/selftest
fasitResources:
  used:
  - alias: appres.cms
    resourceType: baseUrl
  exposed:
  - alias: jobbsokerkompetanseUrl
    resourceType: restservice
    path: /jobbsokerkompetanse
