/* tslint:disable:max-line-length */
export default { 'nb': { 
'cv-overskrift': 'CV-en skal fortelle hvem du er, hva slags utdanning du har og hva du har gjort. Hvor god er CV-en din?',
'din-besvarelse': 'Din besvarelse',
'dine-svar': 'Dine svar',
'ettvalg': 'Marker det alternativet som passer for deg.',
'feilmelding-mangler-svar': 'Du må svare på spørsmålet før du kan gå videre',
'finn-jobb-overskrift': 'Der er mange måter å finne ledige jobber på. Hvordan leter du?',
'flervalg': 'Marker de alternativene som passer for deg.',
'fortsett-knapp': 'Fortsett',
'intervju-overskrift': 'I intervjuet skal du overbevise om at du passer inn i bedriften og at du er et trygt valg. Hvilke erfaringer har du med jobbintervju?',
'overskrift-raad': 'Vi har uthevet 4 råd til deg',
'send-inn': 'Send inn',
'skala': 'Marker på en skala fra 1 til 5 hvor 1 er "utrygg" og 5 er "trygg".',
'soke-erfaring-overskrift': 'Hva er din erfaring som jobbsøker?',
'cv-spm-01': 'Hvor har du registrert CV-en din?',
'cv-spm-02': 'Hvor synlig er du for en arbeidsgiver som leter etter deg?',
'cv-spm-03': 'Tilpasser du CV-en til hver enkelt stillingsannonse?',
'cv-spm-04': 'Hvor etterspurt er kompetansen din på arbeidsmarkedet?',
'cv-spm-05': 'Hvilken erfaring har du med å søke jobber?',
'cv-svar-0101': 'nav.no',
'cv-svar-0102': 'Finn.no',
'cv-svar-0103': 'LinkedIn',
'cv-svar-0104': 'Bemanningsbyråer ol.',
'cv-svar-0105': 'På nettsidene til bedrifter',
'cv-svar-0106': 'Jobb-apper',
'cv-svar-0107': 'Andre steder',
'cv-svar-0108': 'Jeg har ikke registrert CV-en min',
'cv-svar-0201': 'Lite synlig',
'cv-svar-0202': 'Ganske synlig',
'cv-svar-0203': 'Veldig synlig',
'cv-svar-0301': 'Skreddersyr hver CV',
'cv-svar-0302': 'Gjør noen tilpasninger',
'cv-svar-0303': 'Sender samme CV til alle',
'cv-svar-0401': '1',
'cv-svar-0402': '2',
'cv-svar-0403': '3',
'cv-svar-0404': '4',
'cv-svar-0405': '5',
'cv-svar-0501': 'Fått tilbud om jobb gjennom nettverket mitt',
'cv-svar-0502': 'Tatt direkte kontakt med en arbeidsgiver',
'cv-svar-0503': 'Sendt søknad på utlyst stilling',
'cv-svar-0504': 'Sendt en åpen søknad',
'cv-svar-0505': 'Levert en åpen søknad ved personlig oppmøte',
'cv-svar-0506': 'Tilbudt stilling uten å ha søkt',
'cv-svar-0507': 'Lite eller ingen erfaring',
'finn-spm-01': 'Hvor finner du jobber?',
'finn-spm-02': 'Hvor ser du etter jobber?',
'finn-spm-03': 'Søker du på flere type stillinger?',
'finn-spm-04': 'Hva slags ansettelse ser du etter?',
'finn-spm-05': 'Hvor fornøyd er du med måten du leter etter jobb på?',
'finn-svar-0101': 'På internett',
'finn-svar-0102': 'På jobbmesser',
'finn-svar-0103': 'Har registrert abonnement på ledige stillinger',
'finn-svar-0104': 'Følger bedrifter på Facebook, LinkedIn etc',
'finn-svar-0105': 'Bruker jobb-apper som indeed.no og jyb.no',
'finn-svar-0106': 'Sjekker nettsidene til bedrifter',
'finn-svar-0107': 'Bruker nettverket mitt',
'finn-svar-0108': 'Blir "headhuntet" av arbeidsgivere',
'finn-svar-0109': 'Gjennom bemanningsbyråer',
'finn-svar-0110': 'Kontaktet arbeidsgiver direkte',
'finn-svar-0111': 'Annet',
'finn-svar-0201': 'I nærområdet mitt',
'finn-svar-0202': 'Under en times reisevei',
'finn-svar-0203': 'I flere fylker',
'finn-svar-0204': 'I hele landet',
'finn-svar-0205': 'I utlandet',
'finn-svar-0206': 'Ingen begrensninger',
'finn-svar-0301': 'Jeg søker bare på én type stillinger',
'finn-svar-0302': 'Jeg søker på litt forskjellig',
'finn-svar-0303': 'Jeg søker på alt jeg kommer over',
'finn-svar-0401': 'Fast',
'finn-svar-0402': 'Vikariat',
'finn-svar-0403': 'Midlertidig',
'finn-svar-0404': 'Tilkallingshjelp',
'finn-svar-0405': 'Heltid',
'finn-svar-0406': 'Deltid',
'finn-svar-0501': 'Svært fornøyd',
'finn-svar-0502': 'Fornøyd',
'finn-svar-0503': 'Kunne vært bedre',
'finn-svar-0504': 'Misfornøyd',
'intervju-spm-01': 'Hvor trygg er du i en intervjusituasjon?',
'intervju-spm-02': 'Hvordan forbereder du deg til intervju?',
'intervju-spm-03': 'Hvor godt pleier du å gjøre det på intervju?',
'intervju-spm-04': 'Hva har du gjort for å øke sjansene dine for å få en jobb?',
'intervju-spm-05': 'Hvordan vurderer du din egen innsats som jobbsøker?',
'intervju-svar-0101': 'Jeg føler meg ikke trygg eller komfortabel i intervju',
'intervju-svar-0102': 'Jeg føler meg litt utrygg i intervju',
'intervju-svar-0103': 'Jeg føler meg litt trygg i intervju',
'intervju-svar-0104': 'Jeg føler meg ganske trygg i intervju',
'intervju-svar-0105': 'Jeg føler meg veldig trygg i intervju',
'intervju-svar-0201': 'Forbereder meg ikke, tar det som det kommer',
'intervju-svar-0202': 'Jeg vet ikke hvordan man forbereder seg',
'intervju-svar-0203': 'Tenker igjennom hvordan jeg skal kle meg',
'intervju-svar-0204': 'Tenker igjennom hvordan jeg skal oppføre meg',
'intervju-svar-0205': 'Leser om bedriften på forhånd',
'intervju-svar-0206': 'Leser utlysningsteksten og søknaden på nytt',
'intervju-svar-0207': 'Øver på å presentere meg selv',
'intervju-svar-0301': '1',
'intervju-svar-0302': '2',
'intervju-svar-0303': '3',
'intervju-svar-0304': '4',
'intervju-svar-0305': '5',
'intervju-svar-0401': 'Tatt interessetester',
'intervju-svar-0402': 'Benyttet meg av nettverket mitt',
'intervju-svar-0403': 'Gått på jobbsøkerkurs',
'intervju-svar-0404': 'Søkt jobb i flere bransjer',
'intervju-svar-0405': 'Tatt kurs eller etterutdanning',
'intervju-svar-0406': 'Søkt jobber andre steder i landet',
'intervju-svar-0407': 'Engasjert meg i frivillig arbeid',
'intervju-svar-0408': 'Annet',
'intervju-svar-0409': 'Ikke noe spesielt',
'intervju-svar-0501': 'Har ikke begynt å søkte jobber ennå',
'intervju-svar-0502': 'Ikke fornøyd med egen innsats',
'intervju-svar-0503': 'Kan gjøre en større innsats',
'intervju-svar-0504': 'Synes jeg har gjort en brukbar jobb',
'intervju-svar-0505': 'Er veldig fornøyd med egen innsats',
'soke-spm-01': 'Hvor mange stillinger har du søkt siste året?',
'soke-spm-02': 'Hvor mange ganger har du blitt innkalt til intervju det siste året?',
'soke-spm-03': 'Hvor mange ganger stillinger har du fått tilbud om det siste året?',
'soke-spm-04': 'Tilpasser du søknaden til hver enkelt stillingsannonse?',
'soke-svar-0101': 'Ingen',
'soke-svar-0102': '1-5',
'soke-svar-0103': '6-20',
'soke-svar-0104': '21-50',
'soke-svar-0105': '50+',
'soke-svar-0201': 'Ingen',
'soke-svar-0202': 'Noen få',
'soke-svar-0203': 'Flere',
'soke-svar-0301': 'Ingen',
'soke-svar-0302': 'Noen få',
'soke-svar-0303': 'Flere',
'soke-svar-0401': 'Sender samme søknad til alle',
'soke-svar-0402': 'Gjør noen tilpasninger',
'soke-svar-0403': 'Skreddersyr alle søknader'
 }, 'en': {} };