/* tslint:disable:max-line-length */
export default { 'nb': { 
'cv-spm-01-alt': 'Godkjent. Hake.',
'cv-spm-02-alt': 'Finn. Forstørrelsesglass.',
'cv-spm-03-alt': 'Ark og blyant. Skrive CV.',
'cv-spm-04-alt': 'Stjerne.',
'cv-spm-05-alt': 'Forstørrelsesglass.',
'finn-spm-01-alt': 'Stedsmarkør.',
'finn-spm-02-alt': 'Forstørrelsesglass.',
'finn-spm-03-alt': 'Ark med tekst.',
'finn-spm-04-alt': 'Personkort.',
'finn-spm-05-alt': 'Smilefjes.',
'intervju-spm-01-alt': 'Kvinne.',
'intervju-spm-02-alt': 'Personkort.',
'intervju-spm-03-alt': 'Snakkebobler.',
'intervju-spm-04-alt': 'Veske.',
'intervju-spm-05-alt': 'Egenvurdering.',
'soke-spm-01-alt': 'Egenvurdering.',
'soke-spm-02-alt': 'Veske.',
'soke-spm-03-alt': 'Bunke med ark.',
'soke-spm-04-alt': 'Ark og blyant.',
'cv-overskrift': 'CV-en skal fortelle hvem du er, hva slags utdanning du har og hva du har gjort. Hvor god er CV-en din?',
'din-besvarelse': 'Din besvarelse',
'dine-svar': 'Dine svar',
'ettvalg': 'Du må velge ett svaralternativ.',
'feilmelding-mangler-svar': 'Du må svare på spørsmålet før du kan gå videre.',
'finn-jobb-overskrift': 'Der er mange måter å finne ledige jobber på. Hvordan leter du?',
'finn-svar-0111-hjelpetekst': 'Papiravis, oppslagstavler, butikkvinduer mm.',
'flervalg': 'Du kan velge flere svaralternativer.',
'forrige-knapp-start': 'Tilbake til start',
'forrige-knapp': 'Tilbake',
'fortsett-knapp': 'Neste',
'ingress-raad': 'Du har nå svart på alle spørsmålene. Ut fra det du har svart, har vi noen tips til deg som vi tror kan komme til nytte når du søker jobber.',
'intervju-overskrift': 'I intervjuet skal du overbevise om at du passer inn i bedriften og at du er et trygt valg. Hvilke erfaringer har du med jobbintervju?',
'mellomtekst-spm-cv-04': 'Velg på en skala fra 1 til 5, hvor 1 er "ingen etterspørsel" og 5 er "stor etterspørsel".',
'overskrift-raad': 'Jobbsøkertips til deg',
'paginering-av': 'av',
'send-inn': 'Send inn',
'skala': 'Velg på en skala fra 1 til 5 hvor 1 er "svært dårlig" og 5 er "veldig godt".',
'soke-erfaring-overskrift': 'Hva er din erfaring som jobbsøker?',
'cv-spm-01': 'Hvor har du<br>registrert CV-en din?',
'cv-spm-02': 'Hvor synlig er du<br>for en arbeidsgiver som<br>leter etter deg?',
'cv-spm-03': 'Tilpasser du<BR>CV-en til hver enkelt<br>stillingsannonse?',
'cv-spm-04': 'Hvor etterspurt<br>er kompetansen din på<br>arbeidsmarkedet?',
'cv-spm-05': 'Hvilken erfaring<br>har du med<br>å søke jobber?',
'cv-svar-0101': 'nav.no',
'cv-svar-0102': 'Finn.no',
'cv-svar-0103': 'LinkedIn',
'cv-svar-0104': 'Bemanningsbyråer ol.',
'cv-svar-0105': 'På nettsidene til bedrifter',
'cv-svar-0106': 'Jobb-apper',
'cv-svar-0107': 'Andre steder',
'cv-svar-0108': 'Jeg har ikke registrert CV-en min',
'cv-svar-0201': 'Lite synlig',
'cv-svar-0202': 'Ganske synlig',
'cv-svar-0203': 'Veldig synlig',
'cv-svar-0301': 'Skreddersyr hver CV',
'cv-svar-0302': 'Gjør noen tilpasninger',
'cv-svar-0303': 'Sender samme CV til alle',
'cv-svar-0401': '1',
'cv-svar-0402': '2',
'cv-svar-0403': '3',
'cv-svar-0404': '4',
'cv-svar-0405': '5',
'cv-svar-0501': 'Fått tilbud om jobb gjennom nettverket mitt',
'cv-svar-0502': 'Tatt direkte kontakt med en arbeidsgiver',
'cv-svar-0503': 'Sendt søknad på utlyst stilling',
'cv-svar-0504': 'Sendt en åpen søknad',
'cv-svar-0505': 'Levert en åpen søknad ved personlig oppmøte',
'cv-svar-0506': 'Tilbudt stilling uten å ha søkt',
'cv-svar-0507': 'Lite eller ingen erfaring',
'finn-spm-01': 'Hvor finner<br>du jobber?',
'finn-spm-02': 'Hvor ser du<br>etter jobber?',
'finn-spm-03': 'Søker du på flere<br>type stillinger?',
'finn-spm-04': 'Hva slags ansettelse<br>ser du etter?',
'finn-spm-05': 'Hvor fornøyd er<br>du med måten du<br>leter etter jobb på?',
'finn-svar-0101': 'På internett',
'finn-svar-0102': 'På jobbmesser',
'finn-svar-0103': 'Har registrert abonnement på ledige stillinger',
'finn-svar-0104': 'Følger bedrifter på Facebook, LinkedIn etc',
'finn-svar-0105': 'Bruker jobb-apper som indeed.no og jyb.no',
'finn-svar-0106': 'Sjekker nettsidene til bedrifter',
'finn-svar-0107': 'Bruker nettverket mitt',
'finn-svar-0108': 'Blir "headhuntet" av arbeidsgivere',
'finn-svar-0109': 'Gjennom bemanningsbyråer',
'finn-svar-0110': 'Kontaktet arbeidsgiver direkte',
'finn-svar-0111': 'Annet',
'finn-svar-0201': 'I nærområdet mitt',
'finn-svar-0202': 'Under en times reisevei',
'finn-svar-0203': 'I flere fylker',
'finn-svar-0204': 'I hele landet',
'finn-svar-0205': 'I utlandet',
'finn-svar-0206': 'Ingen begrensninger',
'finn-svar-0301': 'Jeg søker bare på én type stillinger',
'finn-svar-0302': 'Jeg søker på litt forskjellig',
'finn-svar-0303': 'Jeg søker på alt jeg kommer over',
'finn-svar-0401': 'Fast',
'finn-svar-0402': 'Vikariat',
'finn-svar-0403': 'Midlertidig',
'finn-svar-0404': 'Tilkallingshjelp',
'finn-svar-0405': 'Heltid',
'finn-svar-0406': 'Deltid',
'finn-svar-0501': 'Svært fornøyd',
'finn-svar-0502': 'Fornøyd',
'finn-svar-0503': 'Kunne vært bedre',
'finn-svar-0504': 'Misfornøyd',
'intervju-spm-01': 'Hvor trygg er du<br>i en intervjusituasjon?',
'intervju-spm-02': 'Hvordan forbereder<br>du deg til intervju?',
'intervju-spm-03': 'Hvor godt pleier du<br>å gjøre det på intervju?',
'intervju-spm-04': 'Hva har du gjort for<br>å øke sjansene dine<br>for å få en jobb?',
'intervju-spm-05': 'Hvordan vurderer<br>du din egen innsats<br>som jobbsøker?',
'intervju-svar-0101': 'Jeg føler meg ikke trygg eller komfortabel på intervju',
'intervju-svar-0102': 'Jeg føler meg litt utrygg på intervju',
'intervju-svar-0103': 'Jeg føler meg litt trygg på intervju',
'intervju-svar-0104': 'Jeg føler meg ganske trygg på intervju',
'intervju-svar-0105': 'Jeg føler meg veldig trygg på intervju',
'intervju-svar-0201': 'Forbereder meg ikke, tar det som det kommer',
'intervju-svar-0202': 'Jeg vet ikke hvordan man forbereder seg',
'intervju-svar-0203': 'Tenker igjennom hvordan jeg skal kle meg',
'intervju-svar-0204': 'Tenker igjennom hvordan jeg skal oppføre meg',
'intervju-svar-0205': 'Leser om bedriften på forhånd',
'intervju-svar-0206': 'Leser utlysningsteksten og søknaden på nytt',
'intervju-svar-0207': 'Øver på å presentere meg selv',
'intervju-svar-0301': '1',
'intervju-svar-0302': '2',
'intervju-svar-0303': '3',
'intervju-svar-0304': '4',
'intervju-svar-0305': '5',
'intervju-svar-0401': 'Tatt interessetester',
'intervju-svar-0402': 'Benyttet meg av nettverket mitt',
'intervju-svar-0403': 'Gått på jobbsøkerkurs',
'intervju-svar-0404': 'Søkt jobb i flere bransjer',
'intervju-svar-0405': 'Tatt kurs eller etterutdanning',
'intervju-svar-0406': 'Søkt jobber andre steder i landet',
'intervju-svar-0407': 'Engasjert meg i frivillig arbeid',
'intervju-svar-0408': 'Annet',
'intervju-svar-0409': 'Ikke noe spesielt',
'intervju-svar-0501': 'Har ikke begynt å søkte jobber ennå',
'intervju-svar-0502': 'Ikke fornøyd med egen innsats',
'intervju-svar-0503': 'Kan gjøre en større innsats',
'intervju-svar-0504': 'Synes jeg har gjort en brukbar jobb',
'intervju-svar-0505': 'Er veldig fornøyd med egen innsats',
'paginering': '{indeks} av {total}',
'soke-spm-01': 'Hvor mange stillinger<br>har du søkt siste året?',
'soke-spm-02': 'Hvor mange ganger<br>har du blitt innkalt til<br>intervju det siste året?',
'soke-spm-03': 'Hvor mange stillinger<br>har du fått tilbud om<br>det siste året?',
'soke-spm-04': 'Tilpasser du søknaden<br>til hver enkelt stillingsannonse?',
'soke-svar-0101': 'Ingen',
'soke-svar-0102': '1-5',
'soke-svar-0103': '6-20',
'soke-svar-0104': '21-50',
'soke-svar-0105': '50+',
'soke-svar-0201': 'Ingen',
'soke-svar-0202': 'Noen få',
'soke-svar-0203': 'Flere',
'soke-svar-0301': 'Ingen',
'soke-svar-0302': 'Noen få',
'soke-svar-0303': 'Flere',
'soke-svar-0401': 'Sender samme søknad til alle',
'soke-svar-0402': 'Gjør noen tilpasninger',
'soke-svar-0403': 'Skreddersyr alle søknader',
'start-knapp': 'Start',
'startside-image-alt': 'Mobiltelefon i venstre hånd.',
'startside-ingress': 'Bruk fem minutter på noen<br>spørsmål og få jobbsøkertips.',
'startside-tittel': 'Hvordan søker du jobber?',
'forberedt-ikke-intervju': 'Vær forberedt på at du kan søke mange jobber uten å bli kalt inn til intervju. Jobb godt med CV-en og søknaden, det øker sjansene dine betraktelig.',
'intervju-fokus': 'Husk at hvis du har blitt kalt inn til et intervju, mener arbeidsgiveren at du er kvalifisert for jobben. I intervjuet bør du fokusere på motivasjon og hva du kan bidra med i bedriften.',
'intervju-hvorfor-deg': 'Arbeidsgiveren er først og fremst opptatt av å høre om hvem du er og hva du kan tilføre bedriften. Forbered deg på å snakke om hvorfor akkurat du bør få jobben.',
'intervju-trygg': 'Når du er godt forberedt til intervjuet føler du deg tryggere og kan framstå som den du ønsker - den beste versjonen av deg selv! Øv deg på intervjusituasjonen.',
'nettverk': 'Husk at nettverket ditt er mer enn bare dine nærmeste venner og familie. Det kan være tidligere arbeidsgivere, lærere, naboer og bekjente.',
'oversikt-soknader': 'Lag en oversikt over alle stillingene du har søkt, kontaktpersoner og hele søknadsprosessen. Da blir det enkelt å gå tilbake hvis en arbeidsgiver tar kontakt. Du kan også opprette en aktivitetsplan på Ditt NAV og holde orden på stillingene der.',
'passer-flere-jobber': 'Selv om kravene i annonsen ikke passer 100 prosent, må du ikke undervurdere deg selv. Kanskje passer kompetansen din til flere jobber enn du tror?',
'registrer-CV': 'Vi vil anbefale deg å registrere CV-en din på enda flere steder enn du gjør i dag, slik at flere arbeidsgivere kan finne deg.',
'sok-utenfor-hjemsted': 'Har du vurdert å søke jobb utenfor hjemstedet ditt? Det kan øke mulighetene dine for å komme raskere i jobb.',
'soknad-svar-paa-annonsen': 'Husk at hver eneste søknad du skriver skal passe til den jobben du søker på. Søknaden skal være et direkte svar på stillingsannonsen.',
'tilpass-cv': 'Både søknaden og CV-en må skrives og tilpasses den jobben du søker på. Søknaden skal svare direkte på stillingsannonsen.',
'tips-standard-overskrift': 'VÅRT TIPS TIL DEG',
'vikariat-deltid': 'Et vikariat eller deltidsjobb kan føre til fast arbeid. Det er lettere å få en ny jobb når du allerede er i arbeid.',
'veiviser-innhold': 'Hvis du ønsker flere jobbsøkertips, se <a href={link}>Bli en bedre jobbsøker steg for steg</a>. Du kan også svare på spørsmålene en gang til.',
'veiviser-link': 'https://tjenester.nav.no/veiviserarbeidssoker/?situasjon=mistet-jobben',
'veiviser-overskrift': 'Gå til vår veiviser for arbeidssøkere'
 }, 'en': {} };