/* tslint:disable */

// const steg = [
// 	{
// 		id: 454198,
// 		tittel: "Begynn med deg selv",
// 		forsidetekst: "",
// 		innhold: "Ta på deg brillene til en arbeidsgiver. Hva skal til for at du ville ansette deg selv?",
// 		ikon: "person",
// 		temaer: [
// 			{
// 				id: 454071,
// 				referanse: "raad-1",
// 				tittel: "Kom i gang",
// 				ingress: "Kom i gang med jobbsøkingen så raskt som mulig.",
// 				aktiviteter: [
// 					{
// 						id: 454041,
// 						tittel: "Sett en startdato for jobbsøking.",
// 						innhold: "De fleste vil oppleve det som tøft å miste jobben. Inntekten går ned, du mister den daglige kontakten med kolleger og framtiden kan virke usikker. Unn deg et par dager til å ta inn over deg det som har skjedd. Men det er viktig at du kommer raskt i gang, sett en dato for når du begynner å søke jobber.",
// 						tags: [
// 							{tag: "mistet-jobben"},
// 							{tag: "permittert"},
// 						],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454067,
//                 referanse: "raad-2",
// 				tittel: "Beskriv kompetansen din",
// 				ingress: "Tenk gjennom hva du har gjort, hva du har lært og hva du kan gjøre.",
// 				aktiviteter: [
// 					{
// 						id: 454042,
// 						tittel: "Beskriv din kompetanse.",
// 						innhold: "Lag en oversikt over hvem du er som person. Hva er motivasjonen din for å søke jobber? Hva er kompetansen din og dine personlige egenskaper? Hva er dine styrker og hva er unikt ved deg? Se flere spørsmål som kan hjelpe deg å tenke i gjennom <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Arbeidsledig+og+jobbsoker/Jobbsokertips/Hva+kan+du\">hva som er din kompetanse</a>. <br/><br/> I noen bransjer legger arbeidsgiveren stor vekt på hvilken kompetanse du har gjennom utdanning og fagopplæring. Det kan være alt fra yrkesfag på videregående til en grad fra høgskole eller universitet. I andre jobber blir det lagt mer vekt på praktiske erfaringer. Realkompetansen din, alle kunnskaper og ferdigheter du har, kan bidra til at du får jobben.<br/><br/> Når du reflekterer over og blir trygg på egen kompetanse, blir det lettere å skrive gode søknader, og du er bedre forberedt til intervjuet. Les mer om <a href=\"https://www.uio.no/studier/karriere/jobbsoking/Dette-ser-arbeidsgiver-etter/kompetanse.html\">kompetanse på uio.no</a>, og om <a href=\"https://www.kompetansenorge.no/realkompetanse/realkompetansevurdering/\" target=\"_blank\">realkompetansevurdering</a> hos Kompetanse Norge. <br/>Lag en oversikt der du beskriver kompetansen din og dine personlige egenskaper. ",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454073,
//                 referanse: "raad-3",
// 				tittel: "Sett deg mål",
// 				ingress: "Det kan være lurt å sette seg noen karrieremål og jobbe mot dem.",
// 				aktiviteter: [
// 					{
// 						id: 454061,
// 						tittel: "Sett deg kortsiktige mål.",
// 						innhold: "Hvilke aktiviteter ønsker og trenger du å gjennomføre de neste månedene eller i løpet av året? Finn ut hvilken kompetanse du trenger for å få den jobben du ønsker deg.<br/>Lag en oversikt over dine kortsiktige mål.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454062,
// 						tittel: "Sett deg langsiktige mål.",
// 						innhold: "Hva ønsker du å jobbe med om 3, 5 eller 10 år? Hvor ønsker du å jobbe? Finn ut hvilken kompetanse du trenger for å få den jobben du ønsker deg.<br/>Lag en oversikt over dine langsiktige mål.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454075,
//                 referanse: "raad-4",
// 				tittel: "Ta en interessetest",
// 				ingress: "En interessetest kan hjelpe deg med å velge utdanning og yrke.",
// 				aktiviteter: [
// 					{
// 						id: 454024,
// 						tittel: "Ta interessetest.",
// 						innhold: "Se <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Test+deg+for+jobb+og+utdanning/interessetester\">interessetester og yrkesvalgprogrammer</a> på nav.no. Ta en eller flere av testene.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454025,
// 						tittel: "Ta utdanningstest.",
// 						innhold: "Ta test for videregående opplæring på <a href=\"https://www2.vilbli.no/?Side=Interessetest&amp;unfinished_krt=1,2&amp;krt=1&amp;nullstill=1\" target=\"_blank\">vilbli.no.</a> Ta utdanningstest i realfaglige og teknologiske yrker på <a href=\"http://www.velgriktig.no/utdanningstesten/\" target=\"_blank\">velgriktig.no</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454043,
// 						tittel: "Finn yrker.",
// 						innhold: "Finn fire yrker i <a href=\"https://utdanning.no/jobbkompasset/interesser.html\" target=\"_blank\">Jobbkompasset på utdanning.no</a> du kan tenke deg å lese mer om.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454076,
//                 referanse: "raad-5",
// 				tittel: "Ta en personlighetstest",
// 				ingress: "En personlighetstest kan gi deg verdifull innsikt om deg selv og dine interesser.",
// 				aktiviteter: [
// 					{
// 						id: 454045,
// 						tittel: "Ta ferdighets- og personlighetstester.",
// 						innhold: "På BIs sider finner du <a href=\"https://at.bi.no/NO/atbi/karriereservice/intervju/ferdighets-og-personlighetstester\" target=\"_blank\">ferdighets- og personlighetstester</a>. Ta en test.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454044,
// 						tittel: "Ta persontypetest.",
// 						innhold: "På <a href=\"https://www.jobbsafari.no/persontypetest\" target=\"_blank\">Jobbsafari.no</a> finner du en  persontypetest.  Ta testen.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454068,
//                 referanse: "raad-6",
// 				tittel: "Gjør avtale med karrieresenter",
// 				ingress: "Offentlige karrieresentre finnes i nesten hele landet. Sentrene tilbyr gratis karriereveiledning og hjelp til å søke jobb for alle over 19 år.",
// 				aktiviteter: [
// 					{
// 						id: 454046,
// 						tittel: "Gjør avtale med karrieresenter.",
// 						innhold: "Målet er at du skal bli kjent med dine egenskaper, interesser og kompetanse og ta gode valg for utdanning, opplæring og arbeid.<br/>Ta kontakt med et <a href=\"http://www.vox.no/Karriereveiledning/offentlige-karrieresentre/\" target=\"_blank\">offentlig karrieresenter</a> og gjør en avtale. ",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454072,
//                 referanse: "raad-7",
// 				tittel: "Meld deg på et kurs",
// 				ingress: "Det kan være at du trenger mer kompetanse for å den jobben du ønsker deg.",
// 				aktiviteter: [
// 					{
// 						id: 454047,
// 						tittel: "Meld deg på et kurs.",
// 						innhold: "Kurs kan være kveldskurs som går over lengre tid, eller kurs som varer en helg eller noen arbeidsdager. Det finnes også kurs som du kan ta bare på nett. Kurs øker kompetansen din og viser arbeidsgivere at du er i stand til å legge ned ekstra innsats for å få jobb. Du kan utvikle deg og bli mer relevant for jobbene du søker på. Tenk bredt, alt fra PC-kurs til presentasjonsteknikker kan gi deg viktig påfyll.<br/>Se <a href=\"http://www.folkeuniversitetet.no/\" target=\"_blank\">Folkeuniversitetet</a>, <a href=\"http://www.kursagenten.no/\" target=\"_blank\">Kursagenten</a> og åpne nettkurs fra norske universiteter og høgskoler på <a href=\"http://www.mooc.no/\" target=\"_blank\">mooc.no</a>.<br/><br/> Mottar du dagpenger? Husk å sjekke om du kan kombinere <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Dagpenger+ved+arbeidsloshet+og+permittering/Relatert+informasjon/dagpenger-og-utdanning\">kurs og dagpenger</a>. Sjekk også om <a href=\"https://www-q4.nav.no/no/NAV+og+samfunn/Kontakt+NAV/NAV+i+ditt+fylke\" target=\"_blank\">NAV har aktuelle kurs</a> i ditt fylke.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454048,
// 						tittel: "Ta norskkurs.",
// 						innhold: "Et godt språk kan være avgjørende når du søker jobb. En CV og søknad med skrivefeil havner fort i feil bunke. Trenger du å <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Arbeidsledig+og+jobbsoker/Jobbsokertips/vil-du-ha-jobb-og-sliter-med-spr%C3%A5k\" target=\"_blank\">forbedre norskkunnskapene</a> dine?",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454198,
// 				referanse: "raad-8",
// 				tittel: "Forbedre norskkunnskapene dine",
// 				ingress: "Gode norskkunnskaper kan være avgjørende når du søker jobb.",
// 				innhold: "Forbedre norsken din. Er du innvandrer, lær deg norsk. Et godt språk kan være avgjørende når du søker jobb. En CV og søknad med skrivefeil havner fort i feil bunke. Et godt språk vil også gir deg flere muligheter på arbeidsmarkedet. Se hvordan du kan <a href=\"https://www.nav.no/no/Person/Arbeid/Arbeidsledig+og+jobbsoker/Jobbsokertips/vil-du-ha-jobb-og-sliter-med-spr%C3%A5k\" target=\"_blank\">forbedre norskkunnskapene</a> dine og hvor du finner kurs.",
// 				tags: [],
// 				collapsable: "false",
// 			},
// 			{
// 				id: 454077,
//                 referanse: "raad-9",
// 				tittel: "Ta mer utdanning",
// 				ingress: "Det kan være at du trenger mer utdanning for å den jobben du ønsker deg.",
// 				aktiviteter: [
// 					{
// 						id: 454049,
// 						tittel: "Ta mer utdanning.",
// 						innhold: "Mottar du dagpenger? Husk å sjekke om du kan kombinere <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Dagpenger+ved+arbeidsloshet+og+permittering/Relatert+informasjon/dagpenger-og-utdanning\">utdanning og dagpenger</a>.<br/>På <a href=\"https://utdanning.no/\" target=\"_blank\">utdanning.no</a> finner du samlet informasjon om alt som gjelder utdanning og skolegang. På <a href=\"https://www.lanekassen.no/\" target=\"_blank\">lånekassen.no</a> kan du lese om mulighetene dine til å få lån og stipend.<br/><br/> Du blir mer attraktiv for arbeidsgivere med mer utdanning. Det gjelder uansett hvilket nivå utdanningen din er på i utgangspunktet.<br/>Hvis du ikke har fullført videregående utdanning, men har muligheten, gjør det.<br/>Går du på skole og lurer på om du skal slutte? Eller lurer du på hva du skal bli? Se <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Ungdom/Utdanning+og+skole\">råd om skole og utdanning</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454070,
//                 referanse: "raad-10",
// 				tittel: "Sjekk om du har krav på voksenopplæring",
// 				ingress: "Det er fylkeskommunen og kommunen din som har ansvaret for voksenopplæring.",
// 				aktiviteter: [
// 					{
// 						id: 454051,
// 						tittel: "Finn ut om du har voksenrett.",
// 						innhold: "Du kan ha rett til videregående skole, kalt <a href=\"https://www.vilbli.no/nb/nb/no/voksenrett-lovfestet-rett-for-voksne/a/023303/\" target=\"_blank\">voksenrett</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454058,
// 						tittel: "Få vurdert realkompetansen din.",
// 						innhold: "Fylkeskommunen har plikt til å sørge for at du får <a href=\"https://www.vilbli.no/nb/nb/no/realkompetansevurdering/a/023306/\" target=\"_blank\">vurdert din realkompetanse</a> på videregående skoles nivå, uansett om du er søker til videregående opplæring eller ikke. Ta kontakt med fylkeskommunen din.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454059,
// 						tittel: "Sjekk grunnskoletilbud.",
// 						innhold: "Ta kontakt med kommunen din for å sjekke tilbud på grunnskolenivå.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454069,
//                 referanse: "raad-10",
// 				tittel: "Google deg selv",
// 				ingress: "Vær klar over at arbeidsgivere ofte sjekker Facebook-profilen din og googler deg.",
// 				aktiviteter: [
// 					{
// 						id: 454060,
// 						tittel: "Slett uønsket informasjon.",
// 						innhold: "Google deg selv. Er det noe du ikke er stolt over på nettet, fjern det. Hvis innholdet ligger på nettsider du ikke kan redigere selv, kan du få hjelp av <a href=\"https://slettmeg.no/\" target=\"_blank\">slettmeg.no</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454074,
//                 referanse: "raad-11",
// 				tittel: "Start egen virksomhet",
// 				ingress: "Har du ambisjoner om å starte for deg selv? De viktigste veivalgene gjøres i starten.",
// 				aktiviteter: [
// 					{
// 						id: 454063,
// 						tittel: "Gjør grunnleggende undersøkelser.",
// 						innhold: "Forberedelser og planlegging er en forutsetning for å etablere en levedyktig virksomhet. Se <a href=\"https://www.altinn.no/no/hjelp-til-regelverk/\">altinn.no</a>, <a href=\"http://www.etablerer.no/\" target=\"_blank\">etablerer.no</a> og <a href=\"http://www.innovasjonnorge.no/\" target=\"_blank\">Innovasjon Norge</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454064,
// 						tittel: "Dagpenger under etablering",
// 						innhold: "Finn ut om du kan ha rett til <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Dagpenger+ved+arbeidsloshet+og+permittering/dagpenger-og-etablering-av-egen-virksomhet--347271\">dagpenger under etablering</a> av egen bedrift.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454065,
// 						tittel: "Sett deg inn i forsikring, pensjon og sykepenger.",
// 						innhold: "På Altinn og nav.no finner du informasjon om <a href=\"https://www.altinn.no/no/Starte-og-drive-bedrift/Registrere/Forsikring-og-pensjon/Forsikring/\" target=\"_blank\">forsikring</a>, <a href=\"https://www.altinn.no/no/Starte-og-drive-bedrift/Registrere/Forsikring-og-pensjon/Pensjon-for-naringsdrivende/\" target=\"_blank\">pensjon</a> og <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Sykmeldt%2C+arbeidsavklaringspenger+og+yrkesskade/Sykepenger/Sykepenger+til+selvstendig+naringsdrivende+og+frilansere\">sykepenger</a> for selvstendig næringsdrivende.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 		],
// 	},
// 	{
// 		id: 454196,
// 		tittel: "Finn jobbene",
// 		forsidetekst: "",
// 		innhold: "Det er mange måter å finne ledige jobber på. Vær litt detektiv!",
// 		ikon: "fabrikk",
// 		temaer: [
// 			{
// 				id: 454089,
//                 referanse: "raad-12",
// 				tittel: "Finn jobben på nav.no ",
// 				ingress: "På nav.no har du oversikt over stillinger i hele landet. Er du fleksibel når det gjelder jobbønske og arbeidssted, øker mulighetene for å komme raskt i jobb.",
// 				aktiviteter: [
// 					{
// 						id: 454053,
// 						tittel: "Registrer CV på nav.no.",
// 						innhold: "Denne tjenesten er åpen for alle, og du kan bruke den uten å være bruker hos NAV. Det er viktig at du <a href=\"https://tjenester-q4.nav.no/sbl/arbeid/registrering;JSESSIONID-arbeid=TenJEypVebw0d4kbjsAZ-DWn?execution=e1s1\">registrerer en så utfyllende CV</a> som mulig. Legg inn jobbønske, kompetanseord og beskriv egenskapene dine, slik at NAV og arbeidsgivere får god oversikt over erfaringene dine.<br/><br/>Hvert år søker tusenvis av arbeidsgivere i CV-basen på jakt etter arbeidskraft. NAV søker også i CV-basen for å finne kandidater til arbeidsgivere som trenger nye medarbeidere. Hold jobbønsket ditt oppdatert, mange arbeidsgivere søker direkte på jobbønske.<br/><br/>Skal du søke dagpenger er det et krav at du har registrert all jobberfaring, utdanning og minst to kompetanseord i tillegg til språkkunnskaper. Husk å føre opp morsmål.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454050,
// 						tittel: "Finn jobber. ",
// 						innhold: "Sjekk <a href=\"https://tjenester-q4.nav.no/stillinger/\">stillingsbasen på nav.no</a>.<br/>På nav.no finner du også informasjon om <a href=\"https://tjenester-q4.nav.no/stillinger/stillinger?valgteBransjer=&amp;valgteYrker=&amp;valgteKommuner=-1&amp;actionEvent.next=S%25C3%25B8k&amp;valgteLandFylker=-1&amp;begrensUtvalg=A&amp;ord=&amp;sort=akt&amp;rpp=20&amp;rv=l&amp;g1=EOSEU\">ledige jobber i EØS</a> og <a href=\"https://tjenester-q4.nav.no/stillinger/stillinger?valgteBransjer=&amp;valgteYrker=&amp;valgteKommuner=-1&amp;actionEvent.next=S%25C3%25B8k&amp;valgteLandFylker=-1&amp;begrensUtvalg=A&amp;ord=&amp;sort=akt&amp;rpp=20&amp;rv=l&amp;g1=resten+av+verden\">resten av verden</a>. Se tips og råd om <a href=\"https://www-q4.nav.no/no/Person/Flere+tema/Arbeid+og+opphold+i+utlandet/Soke+jobb+i+utlandet\">jobbsøk i utlandet</a>.<br/>Vær mobil. Er du fleksibel når det gjelder jobbønske og arbeidssted, øker mulighetene for å komme raskt i jobb. Hvis du har fått tilbud om arbeid på et annet sted enn hjemstedet, kan du på noen vilkår søke om <a href=\"https://tjenester-q4.nav.no/veiledearbeidssoker/mistet-jobben/okonomi-annenstotte?sprak=nb\">reise- og flyttestønad</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454052,
// 						tittel: "Abonner på stillinger på nav.no.",
// 						innhold: "Få varsel på e-post når det kommer nye stillinger: <a href=\"https://tjenester-q4.nav.no/stillinger/\">Søk på stillinger</a> og velg geografisk område. I trefflisten vil du se lenken «Abonner på dette søket». Lag et abonnement.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454057,
// 						tittel: "Søk jobb i utlandet.",
// 						innhold: "På nav.no finner du <a href=\"https://tjenester-q4.nav.no/stillinger/stillinger?valgteBransjer=&amp;valgteYrker=&amp;valgteKommuner=-1&amp;actionEvent.next=S%25C3%25B8k&amp;valgteLandFylker=-1&amp;begrensUtvalg=A&amp;ord=&amp;sort=akt&amp;rpp=20&amp;rv=l&amp;g1=EOSEU\">ledige jobber i EØS</a> og <a href=\"https://tjenester-q4.nav.no/stillinger/stillinger?valgteBransjer=&amp;valgteYrker=&amp;valgteKommuner=-1&amp;actionEvent.next=S%25C3%25B8k&amp;valgteLandFylker=-1&amp;begrensUtvalg=A&amp;ord=&amp;sort=akt&amp;rpp=20&amp;rv=l&amp;g1=resten+av+verden\">resten av verden</a>. Se tips og råd om <a href=\"https://www-q4.nav.no/no/Person/Flere+tema/Arbeid+og+opphold+i+utlandet/Soke+jobb+i+utlandet\">jobbsøk i utlandet</a>.<br/><br/>Hvis du vil søke <a href=\"https://www-q4.nav.no/no/Person/Flere+tema/Arbeid+og+opphold+i+utlandet/Relatert+informasjon/NAV+hjelper+deg+med+%C3%A5+s%C3%B8ke+jobb+i+EU+og+E%C3%98S+og+Sveits\">jobb i EU/EØS-landene og Sveits</a>, kan NAV hjelpe deg gjennom EURES-samarbeidet. Du finner også nyttig informasjon om hva som er særegent når du søker jobb i de ulike landene på EU-portalen, last ned publikasjonen <a href=\"http://bookshop.europa.eu/en/ready-to-make-the-move--pbKE3012898/\" target=\"_blank\">Er du klar til å ta spranget?</a> (Ready to make the move?)",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454091,
//                 referanse: "raad-13",
// 				tittel: "Abonner på stillinger",
// 				ingress: "Det er mange måter å finne ledige jobber på.",
// 				aktiviteter: [
// 					{
// 						id: 454052,
// 						tittel: "Abonner på stillinger på nav.no.",
// 						innhold: "Få varsel på e-post når det kommer nye stillinger: <a href=\"https://tjenester-q4.nav.no/stillinger/\">Søk på stillinger</a> og velg geografisk område. I trefflisten vil du se lenken «Abonner på dette søket». Lag et abonnement.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454055,
// 						tittel: "Abonner på stillinger i flere kanaler.",
// 						innhold: "Bruker du nav.no og finn.no har du oversikt over de fleste jobbene, men se også oversikt over <a href=\"https://www-q4.nav.no/no/Lokalt/Oslo/Jobbportaler+og+vikarbyraer\">andre stillingsbaser.</a> Du kan også google «jobbportaler», «stillingsbaser» osv. og finne flere jobbportaler. Hos noen bedrifter kan du abonnere på ledige stillinger.<br/>Sett opp varsler når det kommer nye stillinger og gjør deg tilgjengelig.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454056,
// 						tittel: "Prøv jobb-apper.",
// 						innhold: "Sjekk apper som <a href=\"http://no.indeed.com/\" target=\"_blank\">indeed</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454805,
//                 referanse: "raad-14",
// 				tittel: "Under 18 år og vil ha jobb",
// 				ingress: "Det kan være mer utfordrende å få jobb når du er under 18 år. Men det finnes muligheter.",
// 				aktiviteter: [
// 					{
// 						id: 454803,
// 						tittel: "Start med en deltids- eller sommerjobb.",
// 						innhold: "Det er færre jobber for deg under 18 år, men de finnes. Hvis du har hatt sommerjobb, kan det være muligheter for deltidsjobb senere. Hvis du ser etter en deltidsjobb, finnes det arbeidsplasser som tilbyr vakter i helger eller på kveldstid som lar seg kombinere med skole. Ung.no har en oversikt over <a href=\"http://www.ung.no/arbeid/jobbjakt/2799_Under_18_og_p%C3%A5_jakt_etter_jobb.html\" target=\"_blank\">jobber for unge</a>.<br/>All jobberfaring teller positivt, og kan sikre deg en bedre jobb senere. Gjør det beste ut av den jobben du har og gjør en skikkelig innsats slik at du får gode referanser til senere. Her er noen jobber du kanskje ikke har tenkt på:<br/>Avisbud/utdeling av reklame, rengjøring, pakking/lagerarbeid/varepåfylling, enkelt kontorarbeid (sortere, kopiere, rydde, sende brev), barnepass/hundepass, butikkmedarbeider.<br/>Sesongjobber:Innhøsting av bær og frukt, eller åker- og hagearbeid, jobber på kafé, i kiosk, på hytteutleie, skianlegg eller campingplass, jobber i fornøyelsesparker som Tusenfryd og Kongeparken, enkelt gartnerarbeid i parker eller på gravlunder, male hus og gjerder.<br/>Når du er under 18 år er det særlig viktig å være klar over dine rettigheter som arbeidstaker. Les mer på <a href=\"http://www.ung.no/arbeid/532_Rettigheter_n%C3%A5r_du_jobber.html\" target=\"_blank\">ung.no</a>. Hvis du har spørsmål om jobb og utdanning, kan <a href=\"http://www.facebook.com/navjobblyst\">NAV Jobblyst på Facebook</a> eller <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Ungdom/Nyheter/nav-jobblyst-p%C3%A5-snapchat\">Snapchat</a> gi deg råd og veiledning.",
// 						tags: [
// 							{tag: "ung-lite-erfaring"},
// 						],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454799,
//                 referanse: "raad-15",
// 				tittel: "Hvordan få jobb som nyutdannet",
// 				ingress: "Du kan ikke forvente å finne drømmejobben med en gang. Ikke være kresen, all jobberfaring er verdifull og kan gi deg muligheter videre.",
// 				aktiviteter: [
// 					{
// 						id: 454798,
// 						tittel: "Søk på mange typer jobber.",
// 						innhold: "Du bør <a href=\"https://tjenester-q4.nav.no/sbl/arbeid/registrering\" title=\"Registrer deg som arbeidssøker\">melde deg som arbeidssøker</a> hos NAV. Som nyutdannet er du vant til å skrive og formulere deg. Dette kan du dra nytte av når du skriver jobbsøknaden og CV-en din. Bruk god tid på disse to dokumentene. Dette er førsteinntrykket arbeidsgiveren får av deg. Kanskje skal du også søke på jobber som du i utgangspunktet ikke hadde tenkt på.<br/>Har du vurdert å <a href=\"https://tjenester-q4.nav.no/veiviserarbeidssoker/454200/454141\">kontakte frivillige organisasjoner</a> eller engasjere deg politisk? Det finnes også praktikantstillinger hvor du kan opparbeide deg erfaring som kan gjøre deg mer attraktiv for arbeidsgivere. Hvis du vil jobbe med kommunikasjon, kan du kontakte magasiner eller blader som trenger skribenter.",
// 						tags: [
// 							{tag: "ung-lite-erfaring"},
// 						],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454808,
//                 referanse: "raad-16",
// 				tittel: "Ung og jobb i utlandet",
// 				ingress: "Jobb i utlandet gir deg både gode språkkunnskaper og unik arbeidserfaring.",
// 				aktiviteter: [
// 					{
// 						id: 454807,
// 						tittel: "Se hvordan unge kan finne jobber i utlandet.",
// 						innhold: "Arbeidserfaring i utlandet kan være en lærerik og spennende opplevelse. Når du er ung kan du for eksempel jobbe et år i en utenlandsk fornøyelsespark eller ha en sommerjobb i et nordisk land. Et utenlandsopphold kan være et pluss når du søker jobb senere, jobb i utlandet gir deg både gode språkkunnskaper og unik arbeidserfaring.<br/>På nav.no finner du informasjon om <a href=\"https://tjenester-q4.nav.no/stillinger/stillinger?valgteBransjer=&amp;valgteYrker=&amp;valgteKommuner=-1&amp;actionEvent.next=S%25C3%25B8k&amp;valgteLandFylker=-1&amp;begrensUtvalg=A&amp;ord=&amp;sort=akt&amp;rpp=20&amp;rv=l&amp;g1=EOSEU\">ledige jobber i EØS</a> og <a href=\"https://tjenester-q4.nav.no/stillinger/stillinger?valgteBransjer=&amp;valgteYrker=&amp;valgteKommuner=-1&amp;actionEvent.next=S%25C3%25B8k&amp;valgteLandFylker=-1&amp;begrensUtvalg=A&amp;ord=&amp;sort=akt&amp;rpp=20&amp;rv=l&amp;g1=resten+av+verden\">resten av verden</a>. Se tips og råd om <a href=\"https://www-q4.nav.no/no/Person/Flere+tema/Arbeid+og+opphold+i+utlandet/Soke+jobb+i+utlandet\">jobbsøk i utlandet</a>. Du kan også lese mer om jobb i utlandet på <a href=\"http://www.unginfo.oslo.no/?post_type=verden&amp;p=471\" target=\"_blank\">unginfo.oslo.no</a>.<br/>I utlandet finnes det <a href=\"https://www-q4.nav.no/no/Person/Flere+tema/Arbeid+og+opphold+i+utlandet/Relatert+informasjon/flere-jobbmuligheter\" title=\"Flere jobbmuligheter\">flere jobbmuligheter</a>. Blant annet <a href=\"https://www-q4.nav.no/no/Person/Flere+tema/Arbeid+og+opphold+i+utlandet/Soke+jobb+i+utlandet/frivillig-arbeid-utvekslinger--1073751052\" title=\"Frivillig arbeid/utvekslinger\">frivillig arbeid</a>, <a href=\"https://www-q4.nav.no/no/Person/Flere+tema/Arbeid+og+opphold+i+utlandet/Soke+jobb+i+utlandet/au-pair--1073751026\" title=\"Au pair\">au pair</a>, <a href=\"https://www-q4.nav.no/no/Person/Flere+tema/Arbeid+og+opphold+i+utlandet/Relatert+informasjon/sesongarbeid\" title=\"Sesongarbeid\">sesongarbeider</a>, <a href=\"https://www-q4.nav.no/no/Person/Flere+tema/Arbeid+og+opphold+i+utlandet/Soke+jobb+i+utlandet/bistandsorganisasjoner--1073746803\" title=\"Bistandsorganisasjoner\">bistandsorganisasjoner</a>.<br/><a href=\"https://www.arbetsformedlingen.se/Globalmeny/Other-languages/Your-first-EURES-job/Ditt-forsta-Eures-jobb.html\" target=\"_blank\">Din første EURES-jobb</a> er en EU-ordning som skal hjelpe deg som er ung med å finne en jobb, en praktikantmulighet eller lærlingplass i et annet EU-land, Norge eller Island. Er du mellom 18 og 35 år kan du få støtte til å reise på jobbintervju i utlandet, til flytteutgifter, til opplæring som språkkurs, og til anerkjennelse av dine kvalifikasjoner.<br/>Nordjobb formidler sommerjobber i Norden for ungdom i aldergruppen 18-30 år, se <a href=\"http://www.nordjobb.org\" target=\"_blank\">informasjon og søknadsskjema</a>.<br/>Søker du jobb eller er praktikant i utlandet er det viktig å være klar over at det kan påvirke <a href=\"https://www-q4.nav.no/no/Person/Flere+tema/Arbeid+og+opphold+i+utlandet/Jobbe+i+utlandet+og+folketrygden/arbeidstaker-i-utlandet\" title=\"Arbeidstaker i utlandet\">medlemskapet i folketrygden</a>. Uten medlemskap i folketrygden har du ikke rett på dekning av medisinske utgifter og du opparbeider heller ikke pensjonsrettigheter.",
// 						tags: [
// 							{tag: "ung-lite-erfaring"},
// 						],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454797,
//                 referanse: "raad-17",
// 				tittel: "Jobber for deg med ekstra utfordringer",
// 				ingress: "Det finnes et stillingsmarked for deg som har noen ekstra utfordringer når du søker jobb.",
// 				aktiviteter: [
// 					{
// 						id: 454796,
// 						tittel: "Jobber for deg med ekstra utfordringer",
// 						innhold: "<a href=\"https://www.jobbforalle.no/ledige-stillinger\" target=\"_blank\">Jobbforalle.no</a> er et stillingsmarked for deg som støter på utfordringer med å få jobber gjennom vanlige rekrutteringskanaler. På nettstedet finner du også tips og råd som kan <a href=\"https://www.jobbforalle.no/for-arbeidssoekere\" target=\"_blank\">øke sjansene dine på arbeidsmarkedet</a>.",
// 						tags: [
// 							{tag: "utenfor-arbeidslivet-lenge"},
// 						],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454096,
//                 referanse: "raad-18",
// 				tittel: "Delta på karrieredager",
// 				ingress: "Som student kan du delta på karrieredager ved universiteter og høyskoler.",
// 				aktiviteter: [
// 					{
// 						id: 454099,
// 						tittel: "Delta på karrieredager.",
// 						innhold: "Ta kontakt med bedrifter på messen som du gjerne vil vite mer om. Spør om bedriften har ledige praksisstillinger, lærlingeordning eller traineeprogram. Legg igjen CV-en din slik at bedriften kan kontakte deg.",
// 						tags: [
// 							{tag: "ung-lite-erfaring"},
// 						],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454090,
//                 referanse: "raad-19",
// 				tittel: "Registrer deg flere steder",
// 				ingress: "En midlertidig jobb kan være et godt alternativ, også hvis du er permittert eller deltidsansatt.",
// 				aktiviteter: [
// 					{
// 						id: 454054,
// 						tittel: "Registrer deg hos bemanningsselskaper.",
// 						innhold: "Finn ut hvilke aktører som kan være aktuelle for deg. De kan kalle seg litt forskjellig, fra vikarbyråer til rekrutteringsselskaper og hodejegerfirmaer. Sjekk hvilke bransjer og type stillinger de jobber med.<br/><br/>En midlertidig jobb kan være et godt alternativ, også hvis du er permittert eller deltidsansatt. Det er en god mulighet til å «få foten i døra» og fører ofte til forlengelser eller fast ansettelse. Stikk innom byrået en gang i uka og vis deg fram, det er viktig å holde kontakten.<br/><br/>Se også <a href=\"https://www-q4.nav.no/no/Lokalt/Oslo/Jobbportaler+og+vikarbyraer\">denne oversikten</a> over jobbportaler, byråer m.m. (noen byråer har vekt på Oslo-området).<br/>Registrer deg hos et byrå.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454097,
//                 referanse: "raad-20",
// 				tittel: "Bruk nettverket ditt ",
// 				ingress: "Noen finner ny jobb gjennom nettverket sitt. Men ikke tro at alle vet at du er på jakt etter jobb.",
// 				aktiviteter: [
// 					{
// 						id: 454100,
// 						tittel: "Lag en oversikt over nettverket ditt.",
// 						innhold: "Kanskje er det venners venner som ser kompetansen din, eller noen du har truffet gjennom idrett, foreldresamarbeid eller organisasjonsliv. Bli bevisst hvilket nettverk du har, kanskje kan du bli anbefalt til en arbeidsgiver som leter etter nye folk.<br/><br/>Du finner informasjon om å finne jobben gjennom eget nettverk på <a href=\"http://karriererad.monster.no/strategi-for-jobbsok/profesjonell-nettverksbygging/finn-jobben-gjennom-eget-nettverk/article.aspx\" target=\"_blank\">karriererad.monster.no.</a><br/>Lag en oversikt over nettverket ditt.",
// 						tags: [],
// 						collapsable: "true",
// 					},
// 					{
// 						id: 454101,
// 						tittel: "Gjør en lunsjavtale.",
// 						innhold: "Avtal lunsj med en bekjent, tidligere kollega eller arbeidsgiver som har et godt kontaktnett. Spør om de kjenner noen som kan være interessert i din erfaring og kompetanse.<br/><br/>Hensikten med lunsjavtalen er å gjøre deg synlig gjennom nettverket ditt. Jo flere du snakker med, jo større sjanse er det for at det dukker opp jobbmuligheter.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454092,
//                 referanse: "raad-21",
// 				tittel: "Bruk sosiale medier i jobbjakten",
// 				ingress: "Det er vanlig at bedrifter benytter sosiale medier som Facebook, Twitter, LinkedIn og blogger når de rekrutterer.",
// 				aktiviteter: [
// 					{
// 						id: 454086,
// 						tittel: "Følg bedrifter i sosiale medier.",
// 						innhold: "Er du interessert i å jobbe i en spesiell bedrift, kan du like eller følge siden deres. Se hvordan bedriften presenterer seg. Du kan fange opp tips og få kunnskaper om jobber, yrker og muligheter du kanskje ikke hadde tenkt deg.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454087,
// 						tittel: "Kontakt en bedrift via sosiale medier. ",
// 						innhold: "Oppsøk en bedrift du er interessert i via sosiale medier og hør om de er på utkikk etter folk.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454088,
// 						tittel: "Del i sosiale medier.",
// 						innhold: "Del på Facebook at du er på jakt etter jobb. Oppfordre vennene dine til å dele innlegget. Du kan også publisere en åpen søknad på Facebook. Se tips om hvordan <a href=\"http://www.dinside.no/okonomi/slik-bruker-du-sosiale-medier-som-jobbsoker/61181095\" target=\"_blank\">bruke sosiale medier</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454094,
//                 referanse: "raad-22",
// 				tittel: "Bruk LinkedIn",
// 				ingress: "Flere arbeidsgivere og rekrutteringsbyråer bruker LinkedIn når de søker etter medarbeidere.",
// 				aktiviteter: [
// 					{
// 						id: 454093,
// 						tittel: "Lag en LinkedIn-profil.",
// 						innhold: "Ta direkte kontakt med arbeidsgivere med profilen din som CV. Meld deg inn i grupper på LinkedIn som er interessante for deg. Sørg for å vise deg fram og bli sett av potensielle arbeidsgivere. Se tips om hvordan <a href=\"http://www.dinside.no/932347/hvordan-bruke-linkedin-riktig\" target=\"_blank\">bruke LinkedIn</a>.<br/>Opprett en LinkedIn-profil.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454095,
//                 referanse: "raad-23",
// 				tittel: "Delta på NAVs jobbmesser ",
// 				ingress: "På jobbmesser kan du treffe arbeidsgivere ansikt til ansikt og knytte kontakter.",
// 				aktiviteter: [
// 					{
// 						id: 454098,
// 						tittel: "Delta på NAVs jobbmesser.",
// 						innhold: "Sjekk på nav.no om det er <a href=\"https://www-q4.nav.no/no/NAV+og+samfunn/Kontakt+NAV/NAV+i+ditt+fylke\">jobbmesser</a> i ditt fylke eller andre steder i landet du kan tenke deg å jobbe. Ta med CV og møt aktuelle arbeidsgivere, du har en unik sjanse til å selge deg inn.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 		],
// 	},
// 	{
// 		id: 454197,
// 		tittel: "Søknaden og CV-en",
// 		forsidetekst: "",
// 		innhold: "Hvis søknaden og CV-en din får deg på intervju, har du gjort mye riktig.",
// 		ikon: "bunke",
// 		temaer: [
// 			{
// 				id: 454152,
//                 referanse: "raad-24",
// 				tittel: "Skriv søknad og CV",
// 				ingress: "Hvis søknaden og CV-en din får deg på intervju, har du gjort mye riktig.",
// 				aktiviteter: [
// 					{
// 						id: 454120,
// 						tittel: "Les stillingsannonsen nøye.",
// 						innhold: "Se hva arbeidsgiveren spør etter. Marker nøkkelordene. Hva slags egenskaper, erfaringer og kompetanse har du som passer til nøkkelordene? Lag en liste du kan bruke når du skal skrive søknaden.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454122,
// 						tittel: "Ring kontaktpersonen.",
// 						innhold: "Hvis du har gode spørsmål, kan du kontakte personen som er oppgitt I stillingsannonsen. Du viser at du er interessert i jobben, og får en mulighet til å gi et godt førsteinntrykk. Merk deg navnet på den du snakker med. Når du skriver søknaden kan du vise til denne samtalen.<br/><br/>Ikke spør om ting du enkelt kan finne svar på selv. Ikke ring bare for å ringe.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454125,
// 						tittel: "Tilpass CV-en og søknaden.",
// 						innhold: "Skriv CV-en først, da er det lettere å skrive søknaden. Både CV-en og søknaden må tilpasses jobben du søker på. Søknaden skal være et direkte svar på stillingsannonsen. Du trenger ikke nødvendigvis å fylle alle kravene i stillingsannonsen, de færreste gjør det. Noe kan være må-krav, andre ting bør-krav. Se våre eksempler på <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Arbeidsledig+og+jobbsoker/Jobbsokertips/Eksempler+p%C3%A5+s%C3%B8knader+og+CV-er\">søknader og CV-er</a>. På <a href=\"http://www.uio.no/studier/karriere/jobbsoking/cv-soknad/eksempler-cv-soknad.html\" target=\"_blank\">uio.no</a>, <a href=\"http://www.unginfo.oslo.no/?post_type=jobb&amp;p=717\" target=\"_blank\">unginfo.no</a> og <a href=\"http://cvnerden.no/cv-mal/\" target=\"_blank\">cvnerden.no</a> finner du også eksempler på CV-er.<br/><br/>Skriv alltid hvorfor du er motivert for stillingen, eller hvorfor du ønsker å jobbe for denne bedriften. Se flere <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Arbeidsledig+og+jobbsoker/Jobbsokertips/Slik+lager+du+en+god+CV\">tips til CV</a> og <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Arbeidsledig+og+jobbsoker/Jobbsokertips/Skriv+en+god+jobbsoknad\">jobbsøknaden</a>. CV-en bør være på maksimalt to sider. Se også <a href=\"https://tjenester-q4.nav.no/veiviserarbeidssoker/sjekkliste/454210\">huskeliste</a> når du skal søke på en konkret stilling.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454128,
// 						tittel: "Be om tilbakemelding på CV-en og søknaden.",
// 						innhold: "Venner og kjente kan gi nyttige innspill på CV-en og søknaden din. Er det noe du kan forbedre?",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454129,
// 						tittel: "Profesjonell hjelp til søknaden.",
// 						innhold: "Det finnes profesjonelle som kan hjelpe deg med å skrive søknader og CV, hvis du har mulighet til å betale for en slik tjeneste. Søk på nettet.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 468039,
// 						tittel: "Ekstra søknadstips for deg med lite jobberfaring.",
// 						innhold: "Skriv en kort søknad, ikke prøv å framstå som du har mer erfaring enn det du har. Ha en tydelig strategi før du begynner å skrive - du må \"selge inn\" det som gjør at du er verdt å satse på.<br/>Skriv om hva du ønsker å oppnå i jobben, om hvorfor du er spesielt motivert for å jobbe på denne arbeidsplassen, eller om kompetanse du har utenom arbeidslivet som gjør at du kan tilføre arbeidsplassen noe de ikke har fra før.<br/>Få gjerne noen som selv har ansatt folk til å se over søknaden din.<br/>Du kan også skille deg ut ved å lage en utradisjonell presentasjon av deg selv (se aktivitet om utradisjonell CV).",
// 						tags: [
// 							{tag: "ung-lite-erfaring"},
// 						],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 455133,
// 						tittel: "Ekstra CV-tips for deg med lite jobberfaring.",
// 						innhold: "Selv om du ikke har hatt en jobb før, er det allikevel mye du kan skrive på CV-en. Arbeidserfaring kan være mer enn formelle jobber. Har du malt huset, vært hundelufter, sittet mye barnevakt, hatt arbeidsuke eller utplassering på skolen? Kanskje du også har klippet plen, vært med i elevrådet, arrangert noe på skolen eller i fritiden eller har du faste arbeidsoppgaver i hjemmet?<br/>Annen erfaring: Sett opp ulike ting som kan være relevant for jobben du søker på: Hvilke språk du snakker eller skriver, om du er god på data, om du kan spesielle programmer eller om du har du tatt kurs på skolen eller på fritiden.<br/>Fritidsinteresser: Dette punktet må ikke være med. Men har du plass kan du skrive kort om hva du driver med på fritiden din. Driver du med en lagsport, så er du sannsynligvis flink til å samarbeide, vant til å jobbe sammen mot et mål og er inkluderende. Liker du for eksempel å skrive, fotografere, tegne, danse eller har andre interesser, så kan du skrive det.",
// 						tags: [
// 							{tag: "ung-lite-erfaring"},
// 						],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454810,
// 				tittel: "Hvordan skrive om hull i CV-en",
//                 referanse: "raad-25",
// 				ingress: "Noen har perioder i livet uten jobb, skole eller andre organiserte aktivitetet på grunn av sykdom, rus, arbeidsledighet, reiser eller andre ting.",
// 				aktiviteter: [
// 					{
// 						id: 454809,
// 						tittel: "Se tips til hva du kan skrive. ",
// 						innhold: "Vær ærlig. Du trenger ikke skrive masse om det, men forklar årsaken hvis du har et opphold som du tror arbeidsgiveren vil reagere på. Ikke lyv eller pynt unødvendig på sannheten.<br/>Ta kontakt. Det kan lønne seg å ringe eller møte opp personlig om du har hull som kan bli tolket negativt av arbeidsgiveren. Det kan gi et bedre inntrykk og du kan lettere forklare årsaken.<br/>Vend situasjonen til din fordel. Du kan få nyttige erfaringer gjennom vanskelige perioder. Hvilke utfordringer møtte du, og hva har du lært av det du har vært gjennom? Har du blitt mer målbevisst, strukturert eller bedre til å samarbeide? Legg vekt på det du kan. Gjør deg ekstra flid med søknaden. Bruk et engasjerende språk og gi arbeidsgiveren lyst til å møte akkurat deg.",
// 						tags: [
// 							{tag: "ung-lite-erfaring"},
// 							{tag: "utenfor-arbeidslivet-lenge"},
// 						],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454374,
//                 referanse: "raad-26",
// 				tittel: "Skaff dokumentasjon på utdanning og attester",
// 				ingress: "Du må kunne dokumentere utdanning og arbeidserfaring gjennom vitnemål og attester.",
// 				aktiviteter: [
// 					{
// 						id: 454131,
// 						tittel: "Skaff vitnemål og attester.",
// 						innhold: "Sjekk at du har vitnemål fra utdanning og attester fra alle arbeidsforhold.<br/><br/>Hvis du ønsker å jobbe i et annet europeisk land, er Europass CV et dokument som presenterer din kompetanse slik at den lett kan forstås i alle europeiske land. Les mer om <a href=\"http://siu.no/Europass\">siu.no/Europass</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454133,
// 						tittel: "Kopier vitnemål og attester.",
// 						innhold: "Ta kopi av alle <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Arbeidsledig+og+jobbsoker/Jobbsokertips/Relatert+informasjon/trenger-du-bekreftelse-p%C3%A5-rett-kopi\">vitnemål og attester</a>. Ta bilde eller skann alle vitnemål og attester. Disse kan du bruke som <a href=\"https://www-q4.nav.no/no/NAV+og+samfunn/Kontakt+NAV/Relatert+informasjon/ta-bilde-av-vedleggene-med-mobilen\">vedlegg i en digital søknad</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454375,
//                 referanse: "raad-27",
// 				tittel: "Sjekk referansene dine",
// 				ingress: "Referansepersoner kan være en tidligere eller nåværende arbeidsgiver, kollegaer, fagforeningskontakter, lærere, trenere eller et medlem i en organisasjon du er med i.",
// 				aktiviteter: [
// 					{
// 						id: 454822,
// 						tittel: "Ung og få referanser.",
// 						innhold: "Det er vanlig at din forrige arbeidsgiver står som referanse. Har du ikke hatt jobb før, kan du for eksempel be en ansatt på fritidsklubben, lærer, trener eller en annen voksen som kjenner deg om å være referanse. Hvis du har andre alternativer, bør du ikke be foreldre eller venner om å være referanser.",
// 						tags: [
// 							{tag: "ung-lite-erfaring"},
// 						],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454134,
// 						tittel: "Forbered referansene dine.",
// 						innhold: "Du må alltid spørre om personen er villig til å være referanse for deg. Du kan også spørre om hva de vil si om deg. Vær kritisk til hvem du oppgir som referanser. De bør kjenne deg godt og være positivt innstilt til deg. Forbered referansene dine på at en arbeidsgiver kan ringe.<br/><br/>Se flere tips om hva du <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Arbeidsledig+og+jobbsoker/Jobbsokertips/Slik+lager+du+en+god+CV#Referanser\">bør huske på</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 466769,
// 						tittel: "Hold oversikt over referansene.",
// 						innhold: "Du kan velge å oppgi referanser i CV-en, i søknaden, eller skrive at du oppgir referanser ved behov. Du kan også oppgi referanser i intervjuet.<br/>Lag en oversikt over referansene dine. En enkel tabell med noen felter gjør nytten: Navn, bedrift, tittel, e-post, telefon, relasjonen deres når dere jobbet sammen (for eksempel min avdelingsleder). Denne oversikten kan du også gi til arbeidsgiveren når det er aktuelt. Se tabell og mer <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Arbeidsledig+og+jobbsoker/Jobbsokertips/Slik+lager+du+en+god+CV#Referanser\">informasjon om referanser</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454376,
//                 referanse: "raad-28",
// 				tittel: "Logg jobbene du søker på ",
// 				ingress: "En jobblogg er et verktøy som hjelper deg med å holde oversikt over jobbene du har søkt på.",
// 				aktiviteter: [
// 					{
// 						id: 454139,
// 						tittel: "Opprett jobblogg i Ditt NAV.",
// 						innhold: "Før <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Arbeidsledig+og+jobbsoker/Jobbsokertips/Jobblogg\">jobblogg</a> regelmessig. Legg inn informasjon om hver enkelt stilling du søker på, hvilke personer du har vært i kontakt med og hvilke intervjuer du har vært på.<br/><br/>Huk av for at du vil dele jobbloggen med NAV. Da samtykker du i at den informasjon du lagrer på Jobblogg blir synlig for NAV-veilederen din. Slik blir det enklere for NAV å følge deg opp.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454378,
//                 referanse: "raad-29",
// 				tittel: "Send en åpen søknad",
// 				ingress: "Selv om bedriften ikke har lyst ut ledige stillinger, kan du sende en åpen søknad.",
// 				aktiviteter: [
// 					{
// 						id: 454144,
// 						tittel: "Send en åpen søknad.",
// 						innhold: "Finn bedrifter du kan tenke deg å jobbe for, og send jobbsøknader selv om arbeidsgiver ikke har lyst ut noen ledige stillinger.<br/>Send en e-post til en konkret person i bedriften. I en åpen søknad må du legge ekstra vekt på å markedsføre deg selv. Hva kan du bidra med på akkurat denne arbeidsplassen? Hvis mulig, bør du legge ved noe, eller inkludere lenker som viser hvem du er eller hva du kan. Vis at du skjønner hva bedriften driver med. Du kan også fortelle om deg selv og hva slags person du er – nevn personlige egenskaper som beskriver deg.<br/>Til slutt sier du at gjerne kommer innom og tar en prat med personen du sender søknaden til. Legg ved CV-en din.<br/>Tilpass søknaden etter bedrift, bransje og stillingstypen du søker. Hos noen store bedrifter kan du registrere en åpen jobbsøknad på nettsiden deres.<br/>Her finner du <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Arbeidsledig+og+jobbsoker/Jobbsokertips/Skriv+en+god+jobbsoknad#apensoknad\">to eksempler</a> på åpne søknader. Den første er mer målrettet enn den andre – prøv å gjøre din like målrettet som det første eksempelet. Les mer om åpen søknad på <a href=\"https://www.uio.no/studier/karriere/jobbsoking/cv-soknad/eksempler-cv-soknad.html\" target=\"_blank\">uio.no</a>, <a href=\"http://cvnerden.no/eksempler-pa-cv-og-soknad-2/\" target=\"_blank\">cvnerden.no</a>, <a href=\"http://jobbs%C3%B8knader.no/apen-soknad/\" target=\"_blank\">jobbsøknader.no</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454146,
// 						tittel: "Følg opp søknaden.",
// 						innhold: "Det er ingen frister å forholde seg til, bedriften har ikke lyst ut en stilling,  Ring bedriften etter et par uker, hvis du ikke har hørt noe.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454148,
// 						tittel: "Oppsøk bedrifter direkte.",
// 						innhold: "Ta med en åpen søknad eller CV-en. Finn ut hvem i bedriften som er riktig person å snakke med og forsøk å få en kort prat.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454149,
// 						tittel: "Sjekk doffin.no.",
// 						innhold: "<a href=\"https://doffin.no\" target=\"_blank\">Doffin.no</a> er databasen for offentlige innkjøp. Her kan du se hvilke firmaer som vinner anbudskonkurranser, og som kan ha behov for å rekruttere nye medarbeidere.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454377,
//                 referanse: "raad-30",
// 				tittel: "Lag en utradisjonell søknad eller CV ",
// 				ingress: "I noen bransjer gjelder det å skille seg ut. En annerledes søknad eller CV kan bidra til at du får jobben.",
// 				aktiviteter: [
// 					{
// 						id: 454143,
// 						tittel: "Lag en annerledes presentasjon.",
// 						innhold: "Presenter deg selv gjennom en kort video, bilder, en webside eller infografikk. Få inspirasjon på <a href=\"https://www.easel.ly/\" target=\"_blank\">easel.ly</a>, <a href=\"http://vizualize.me\" target=\"_blank\">vizualize.me</a>, <a href=\"https://www.kickresume.com/\" target=\"_blank\">kickresymé</a> og søk på YouTube eller Google.<br/><br/> Vurder først om en annerledes presentasjon er et riktig valg for den jobben du søker på.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 		],
// 	},
// 	{
// 		id: 454199,
// 		tittel: "Intervjuet",
// 		forsidetekst: "",
// 		innhold: "Jobbintervjuet kan virke skummelt. Er du godt forberedt, senker du skuldrene.",
// 		ikon: "personer",
// 		temaer: [
// 			{
// 				id: 454119,
//                 referanse: "raad-31",
// 				tittel: "Finn ut hva slags intervju du skal på ",
// 				ingress: "Det tradisjonelle intervjuet ansikt til ansikt med en arbeidsgiver er fortsatt det mest vanlige, men det finnes flere intervjuformer.",
// 				aktiviteter: [
// 					{
// 						id: 454103,
// 						tittel: "Finn ut hva slags intervju du skal på.",
// 						innhold: "Er det et tradisjonelt intervju, telefonintervju, videointervju eller et gruppeintervju? Personlighets- og ferdighetstester kan også være en del av intervjuprosessen. Det er vanlig med flere intervjurunder, noen ganger med både intervjuer og tester. <a href=\"https://karrierestart.no/jobbintervju/436-jobbintervju-8-ulike-typer-intervjuer\" target=\"_blank\">Se karrierestart.no</a> , <a href=\"https://at.bi.no/NO/SiteAssets/tjenester/karriereservice/cv-og-s%C3%B8knad/car_cv-eksempler/Jobbs%C3%B8king%202014.pdf\" target=\"_blank\">bi.no</a> og Youtube for eksempler på ulike intervjuformer.<br/>Ganske ofte vil du oppleve at flere er til stede under intervjuet, for eksempel hvis du søker en offentlig stilling. Da kan gjerne en tillitsvalgt og også folk fra personalkontoret være til stede. Du vil kanskje lure på om du bare skal forholde deg til intervjueren, eller om du også skal forholde deg til de andre i rommet.<br/>Intervjuer vil være forskjellige, men selv om det er intervjueren du i hovedsak forholder deg til bør du vise at du oppfatter at de andre er til stede og at du anerkjenner dem. Gi alle et godt håndtrykk før og etter intervjuet.<br/>Du kan også bli intervjuet av et rekrutteringsbyrå på vegne av arbeidsgiveren.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454121,
//                 referanse: "raad-32",
// 				tittel: "Forbered deg til intervjuet ",
// 				ingress: "I intervjuet skal du overbevise om at du passer inn i bedriften og at du er et trygt valg.",
// 				aktiviteter: [
// 					{
// 						id: 454104,
// 						tittel: "Forbered deg på intervjuspørsmål.",
// 						innhold: "Mange spørsmål går igjen fra intervju til intervju. Noter hva du vil svare på <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Arbeidsledig+og+jobbsoker/Jobbsokertips/Slik+forbereder+du+deg+til+jobbintervju\">vanlige</a> og <a href=\"http://www.arbeidsom.no/jobbtips/forbered-deg-pa-de-uventede-intervjusporsmalene/\" target=\"_blank\">uventede</a> intervjuspørsmål. Er det et spørsmål du føler du ikke har et godt svar på, ta deg tid og svar så godt du kan. Det viktigste er at du er deg selv i intervjuet. Svar ut fra det du tenker og føler, legg vekt på det du kan og selg deg selv – ikke vær beskjeden. Hvis du viser at du er reflektert i et jobbintervju, er det et stort pluss.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454105,
// 						tittel: "Forbered presentasjon av deg selv.",
// 						innhold: "Forbered en kort, muntlig presentasjon som viser hvem du er som person, dine personlige egenskaper og interesser. Legg vekt på det du ikke har skrevet i CV-en og søknaden, det som sier noe om deg som menneske.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454106,
// 						tittel: "Les papirene dine før intervjuet.",
// 						innhold: "Gå gjennom stillingsannonsen, søknaden og CV-en din på nytt før intervjuet.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454806,
//                 referanse: "raad-33",
// 				tittel: "Intervjutips for deg som er ung",
// 				ingress: "Det kan være nervepirrende å møte opp på sitt første jobbintervju. Vær godt forberedt, men hva bør du forberede deg på? ",
// 				aktiviteter: [],
// 			},
// 			{
// 				id: 454123,
//                 referanse: "raad-34",
// 				tittel: "Hva er dine sterke sider ",
// 				ingress: "Når du blir spurt om dine sterke sider er det din sjanse til å si hva du er god på.",
// 				aktiviteter: [
// 					{
// 						id: 454107,
// 						tittel: "Lag liste med sterke sider.",
// 						innhold: "Forbered en liste med tre til fem sterke sider. Du kan tenke lenger enn jobbsituasjoner, også gjennom utdanning, organisasjonsliv og lignende får du vist og utviklet dine sterke sider. Hvis du synes det er vanskelig, tenk på hva andre vil beskrive som dine sterke sider.<br/><br/>For hver sterk side, skriv ned et eksempel fra din karriere eller fritid der du har brukt og fått vist denne egenskapen. Skriv så ned hvordan du tror du kan få brukt de sterke sidene dine hos den nye arbeidsgiveren. Se tips på <a href=\"http://karriererad.monster.no/intervju/intervjusporsmal/hva-er-dine-sterke-og-svake-sider/article.aspx\" target=\"_blank\">karriererad.monster.no</a>.",
// 						tags: [],
// 						collapsable: "true",
// 					},
// 				],
// 			},
// 			{
// 				id: 454124,
//                 referanse: "raad-35",
// 				tittel: "Hva er dine svake sider",
// 				ingress: "En arbeidsgiver vil ofte utfordre deg til å si noe også om dine svake sider.",
// 				aktiviteter: [
// 					{
// 						id: 454108,
// 						tittel: "Lag liste med svake sider.",
// 						innhold: "Noter egenskaper ved deg selv som du ikke er helt fornøyd med. Har dette betydning for jobben, samarbeid med kolleger eller hvordan du kommuniserer? Er du i stand til å formidle egenskapene dine på en troverdig og gjennomtenkt måte? Kan du snu noe negativt til noe som også er positivt?<br/>Forbered et par ting du kan svare kort og greit på. Du trenger ikke fortelle mye om personlige forhold. Du skal bare formidle litt selvinnsikt og vise at du kan snakke om ting du trenger å jobbe med på en rolig og avslappet måte.<br/>Hvis du trener på å bli bedre på noe du ikke er så god på, for eksempel gjennom kurs eller gjør andre aktiviteter, viser du at du jobber med å bli en stadig bedre arbeidssøker. Se også tips på <a href=\"http://studenttorget.no/index.php?show=4793&amp;expand=4631,4793&amp;artikkelid=11773\">studenttorget.no</a>. ",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454126,
//                 referanse: "raad-36",
// 				tittel: "Øv på intervjusituasjonen",
// 				ingress: "Øvelse gjør mester, det gjelder også intervjusituasjonen.",
// 				aktiviteter: [
// 					{
// 						id: 454109,
// 						tittel: "Øv på intervjuet.",
// 						innhold: "Hva vil du si? Spør familie eller venner om hjelp til å trene på intervjusituasjonen, eller tren selv foran speilet. Tenk gjennom dine egne grenser for hvor privat du vil være. Arbeidsgiver har ikke rett til å vite politisk orientering, seksuell legning, hvilken religion du tilhører eller om du er fagorganisert.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454110,
// 						tittel: "Lag en plan for etterlatt inntrykk.",
// 						innhold: "Hvordan vil du skape det inntrykket du ønsker? Klarer du å overbevise arbeidsgiveren om at du er trygt valg? Klarer du å formidle at du virkelig vil ha jobben? Hva tror du arbeidsgiveren vil tenke etter intervjuet, hva blir det etterlatte inntrykket?",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454111,
// 						tittel: "Profesjonell intervjutrening.",
// 						innhold: "Har du råd til å betale en profesjonell coach eller rådgiver for å få intervjutrening? Søk på nettet. Noen rådgivere tilbyr personlige utviklingsprogram som kan hjelpe deg i hele jobbsøkerprosessen.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454127,
//                 referanse: "raad-37",
// 				tittel: "Gjør et godt førsteinntrykk",
// 				ingress: "Førsteinntrykket kan avgjøre om du får jobben.",
// 				aktiviteter: [
// 					{
// 						id: 454112,
// 						tittel: "Gjør et godt førsteinntrykk.",
// 						innhold: "Tilpass antrekket ditt til jobben du søker på. Rene, hele og pene klær forsterker inntrykket av deg som en seriøs kandidat. Legg vekt på personlig hygiene, vær nydusjet og nybarbert, dropp røyken og ha et generelt velstelt ytre. Bruk deodorant eller annen godlukt, men ikke overdriv. Et fast håndtrykk og god blikkontakt gir et tillitvekkende inntrykk.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454113,
// 						tittel: "Møt i rett tid til intervjuet.",
// 						innhold: "Husk hvilken avdeling du skal til og hvem som er kontaktperson for stillingen. Ta med deg notater, CV, søknad, attester og vitnemål til intervjuet. Ha et sett med kopier som arbeidsgiveren kan få.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454130,
//                 referanse: "raad-38",
// 				tittel: "Still spørsmål til bedriften",
// 				ingress: "Benytt anledningen til å stille spørsmål som viser at du har forstått hva som er viktig for denne arbeidsgiveren.",
// 				aktiviteter: [
// 					{
// 						id: 454114,
// 						tittel: "Lag liste med spørsmål til arbeidsgiver.",
// 						innhold: "Ta med gode spørsmål som viser at du har forberedt deg til intervjuet. Les mer på <a href=\"http://karriererad.monster.no/intervju/forberedelse-til-intervju/hvilke-sporsmal-skal-jeg-stille-den-som-intervjuer-meg/article.aspx\" target=\"_blank\">karriererad.monster.no</a>.<br/><br/>Vær lydhør og vis evne til å lytte. Vær opptatt av å møte arbeidsgiverens forventninger og behov. Still spørsmål eller kommenter når dette er passende, men unngå å avbryte intervjueren. Vær forberedt på overraskende spørsmål. Se tips hos <a href=\"https://www.visma.no/bemanning/for-jobbsokere/hvordan-gjore-et-godt-intervju/\" target=\"_blank\">visma.no</a>. Se også <a href=\"http://www.arbeidsom.no/\" target=\"_blank\">arbeidsom.no</a>.<br/><br/>Vent med spørsmål om lønn til den som intervjuer deg tar opp temaet. Ofte vil lønn først være et tema på et annengangs intervju, eller hvis du får tilbud om jobben.",
// 						tags: [],
// 						collapsable: "true",
// 					},
// 				],
// 			},
// 			{
// 				id: 454132,
//                 referanse: "raad-39",
// 				tittel: "Hvordan gikk intervjuet ",
// 				ingress: "Bruk tid på å evaluere innsatsen din etter hvert intervju.  ",
// 				aktiviteter: [
// 					{
// 						id: 454115,
// 						tittel: "Evaluer innsatsen din i intervjuet.",
// 						innhold: "Hva fungerte godt og hva fungerte mindre bra? Hvor god var du til å lytte? Stilte du relevante spørsmål til arbeidsgiver? Ga du klart uttrykk for at du var interessert i jobben? Klarte du å knytte interesser, utdannelse og erfaring til jobben? Fikk du frem de sidene ved deg selv som var viktige for jobben? Hvor godt forberedt var du? Hva kan du gjøre annerledes neste gang?",
// 						tags: [],
// 						collapsable: "true",
// 					},
// 					{
// 						id: 454116,
// 						tittel: "Noter spørsmål og svar.",
// 						innhold: "Noter spørsmål du svarte godt på og hva du svarte, slik at du husker det til neste gang. Hvilke spørsmål svarte du ikke så godt på? Hva ønsker du å svare neste gang du kommer til intervju?",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454117,
// 						tittel: "Del intervjuerfaringen.",
// 						innhold: "Del erfaringen med en venn eller kollega og få tilbakemelding på hva du kan gjøre annerledes.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454135,
//                 referanse: "raad-40",
// 				tittel: "Fikk du ikke jobben ",
// 				ingress: "Ta kontakt med arbeidsgiveren hvis du ikke fikk jobben. Du kan få tilbakemeldinger som hjelper deg videre.",
// 				aktiviteter: [
// 					{
// 						id: 454118,
// 						tittel: "Be om tilbakemelding fra arbeidsgiver på intervjuet.",
// 						innhold: "Be om tips til hva du kan gjøre bedre eller annerledes. Hvordan opplevde de deg og måten du svarte på? Ga du nok av deg selv? Hvordan oppfattet de søknaden og CV-en din? Skriv ned forbedringspunkter og bruk dem i forberedelsene til neste intervju. Du har ikke krav på en slik tilbakemelding, men mange arbeidsgivere vil kunne gi deg det.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 		],
// 	},
// 	{
// 		id: 454200,
// 		tittel: "Hverdagen som arbeidssøker",
// 		forsidetekst: "",
// 		innhold: "Det er krevende å holde motivasjonen oppe. Det hjelper å ha en plan.",
// 		ikon: "hus",
// 		temaer: [
// 			{
// 				id: 454137,
//                 referanse: "raad-41",
// 				tittel: "Lag en plan",
// 				ingress: "Vær forberedt på at jobbsøking kan være en lang prosess. Tenk måneder, ikke uker. Sett av god tid til jobbsøking, det er en fulltidsjobb.",
// 				aktiviteter: [
// 					{
// 						id: 454145,
// 						tittel: "Lag struktur på dagen.",
// 						innhold: "Søk jobber innenfor normal arbeidstid. På ettermiddagen har du fri og kan gjøre andre aktiviteter.<br/><br/> Hvis du har lett for å snu døgnet, kan det føre til dårlige rutiner. Oppsøk jobbklubber og lignende som hjelper deg med å stå opp til vanlig tid.",
// 						tags: [
// 							{tag: "ung-lite-erfaring"},
// 							{tag: "utenfor-arbeidslivet-lenge"},
// 							{tag: "permittert"},
// 							{tag: "mistet-jobben"},
// 						],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454147,
// 						tittel: "Lag en ukeplan.",
// 						innhold: "Noter stillinger du skal søke på og når du skal sende søknaden. Noter også hvilke bedrifter du skal kontakte og når. Bruk <a href=\"https://tjenester-q4.nav.no/aktivitetsplan/\">aktivitetsplanen</a>.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454138,
//                 referanse: "raad-42",
// 				tittel: "Reflekter over jobbene du søker på ",
// 				ingress: "Det er helt vanlig å søke mange jobber uten å få napp. Er du fleksibel nok?",
// 				aktiviteter: [
// 					{
// 						id: 454150,
// 						tittel: "Tenk gjennom hvilke stillinger du søker på.",
// 						innhold: "Har du vært lenge ledig? Det trenger ikke bety at det er noe galt med deg, mange søker på den samme stillingen.<br/><br/> Søker du på de riktige jobbene? Er du fleksibel nok, søker du på flere typer jobber? Ikke lås deg til ett yrke eller en bransje. Vær åpen for alle muligheter. Da er det større sjanse for at du finner en jobb.<br/><br/> Kan du senke kravene litt? Søker du <a href=\"https://tjenester-q4.nav.no/veiledearbeidssoker/mistet-jobben/okonomi-annenstotte?sprak=nb\">flere steder i landet</a>? Kan du ta noe midlertidig eller en deltidsjobb? Dukker det opp småjobber, vikariater eller sommerjobber, grip muligheten mens du venter på fulltidsjobb. Alt hjelper og gir påfyll på CV-en.<br/><br/> Har du sendt hundrevis av søknader uten å få napp? Ikke tro at alt er forgjeves selv om du ikke får jobben. Du utvikler deg som jobbsøker. Formuleringene og setningene dine blir bedre og du blir flinkere til å selge deg inn.",
// 						tags: [
// 							{tag: "ung-lite-erfaring"},
// 							{tag: "utenfor-arbeidslivet-lenge"},
// 							{tag: "permittert"},
// 							{tag: "mistet-jobben"},
// 						],
// 						collapsable: "true",
// 					},
// 				],
// 			},
// 			{
// 				id: 454140,
//                 referanse: "raad-43",
// 				tittel: "Vær aktiv ",
// 				ingress: "Sett av tid til aktiviteter utenom jobbsøkingen.",
// 				aktiviteter: [
// 					{
// 						id: 454151,
// 						tittel: "Delta på aktiviteter.",
// 						innhold: "Vær sosial, plei vennskap og familierelasjoner. Hold deg i form, tren, gå turer og få energi. Delta på aktiviteter som gir deg overskudd i hverdagen.",
// 						tags: [
// 							{tag: "ung-lite-erfaring"},
// 							{tag: "utenfor-arbeidslivet-lenge"},
// 							{tag: "permittert"},
// 							{tag: "mistet-jobben"},
// 						],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454047,
// 						tittel: "Meld deg på et kurs.",
// 						innhold: "Kurs kan være kveldskurs som går over lengre tid, eller kurs som varer en helg eller noen arbeidsdager. Det finnes også kurs som du kan ta bare på nett. Kurs øker kompetansen din og viser arbeidsgivere at du er i stand til å legge ned ekstra innsats for å få jobb. Du kan utvikle deg og bli mer relevant for jobbene du søker på. Tenk bredt, alt fra PC-kurs til presentasjonsteknikker kan gi deg viktig påfyll.<br/>Se <a href=\"http://www.folkeuniversitetet.no/\" target=\"_blank\">Folkeuniversitetet</a>, <a href=\"http://www.kursagenten.no/\" target=\"_blank\">Kursagenten</a> og åpne nettkurs fra norske universiteter og høgskoler på <a href=\"http://www.mooc.no/\" target=\"_blank\">mooc.no</a>.<br/><br/> Mottar du dagpenger? Husk å sjekke om du kan kombinere <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Dagpenger+ved+arbeidsloshet+og+permittering/Relatert+informasjon/dagpenger-og-utdanning\">kurs og dagpenger</a>. Sjekk også om <a href=\"https://www-q4.nav.no/no/NAV+og+samfunn/Kontakt+NAV/NAV+i+ditt+fylke\" target=\"_blank\">NAV har aktuelle kurs</a> i ditt fylke.",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 					{
// 						id: 454048,
// 						tittel: "Ta norskkurs.",
// 						innhold: "Et godt språk kan være avgjørende når du søker jobb. En CV og søknad med skrivefeil havner fort i feil bunke. Trenger du å <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Arbeidsledig+og+jobbsoker/Jobbsokertips/vil-du-ha-jobb-og-sliter-med-spr%C3%A5k\" target=\"_blank\">forbedre norskkunnskapene</a> dine?",
// 						tags: [],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454141,
//                 referanse: "raad-44",
// 				tittel: "Delta i frivillig arbeid",
// 				ingress: "Frivillig arbeid gir deg erfaring, kompetanse og sosial kontakt, og er bra å ha på CV-en.",
// 				aktiviteter: [
// 					{
// 						id: 454153,
// 						tittel: "Kontakt frivillige organisasjoner.",
// 						innhold: "Sett av noen timer hver uke til frivillig arbeid eller annet organisasjonsarbeid. Du kan oppleve meningsfylt arbeid, få et større nettverk og komme over nye jobbmuligheter.<br/><br/> Google frivillige organisasjoner som <a href=\"http://frivilligsentral.no/\" target=\"_blank\">frivillighetssentralene</a>, <a href=\"https://www.rodekors.no/\" target=\"_blank\">Røde Kors</a>, <a href=\"http://www.bymisjon.no/\">Kirkens bymisjon</a> og <a href=\"http://www.folkehjelp.no/\" target=\"_blank\">Norsk Folkehjelp</a>. Du kan også se siden til <a href=\"https://frivillig.no/\" target=\"_blank\">frivillig.no</a>.<br/><br/>Vær klar over at frivillig arbeid kan gå utover retten din til å motta dagpenger. Les mer om <a href=\"https://www-q4.nav.no/rettskildene/Rundskriv/%C2%A7+4-6.+Dagpenger+under+utdanning,+oppl%C3%A6ring,+etablering+av+egen+virksomhet+m.v..354595.cms#Frivlillhetsarbeid\">reglene for frivillig arbeid og dagpenger</a>.",
// 						tags: [
// 							{tag: "ung-lite-erfaring"},
// 							{tag: "utenfor-arbeidslivet-lenge"},
// 							{tag: "permittert"},
// 							{tag: "mistet-jobben"},
// 						],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 			{
// 				id: 454142,
//                 referanse: "raad-45",
// 				tittel: "Meld deg på jobbsøkerkurs  ",
// 				ingress: "Trenger du å bli en bedre jobbsøker? Er du usikker på om du skriver gode nok søknader, eller trenger du å trene på intervjuer?",
// 				aktiviteter: [
// 					{
// 						id: 454159,
// 						tittel: "Meld deg på et jobbsøkerkurs.",
// 						innhold: "Finn ut om <a href=\"https://www-q4.nav.no/no/NAV+og+samfunn/Kontakt+NAV/NAV+i+ditt+fylke\">NAV i ditt fylke</a> har tilbud og ledige plasser på <a href=\"https://www-q4.nav.no/no/Person/Arbeid/Oppfolging+og+tiltak+for+a+komme+i+jobb/Tiltak+for+a+komme+i+jobb/Relatert+innhold/jobbklubb\">jobbklubb</a>. Ta kontakt med NAV og hør om NAV kan melde deg på dette kurset.",
// 						tags: [
// 							{tag: "ung-lite-erfaring"},
// 							{tag: "utenfor-arbeidslivet-lenge"},
// 							{tag: "permittert"},
// 							{tag: "mistet-jobben"},
// 						],
// 						collapsable: "false",
// 					},
// 				],
// 			},
// 		]
// 	}
// ];
